### ISSUE TITLE
Add some more tests for the pytest plugin

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/contract-deploy-tools#17]
We could add some more tests for the pytest plugin.

**Comment by cducrest** [comment]
I add some tests for the option `--contracts-dir` as its behaviour was not clear to me and not thoroughly tested. I believe the behaviour of `get_contracts_folder` with the option is correct this way.

I find it disturbing that the tests fail if you run them from the `contracts-deploy-tools/tests` directory. But I believe this is the expected behaviour of the end to end tests, as we pass it the option `--contracts-dir testcontracts` in https://github.com/trustlines-network/contract-deploy-tools/blob/feature/add-tests-for-plugin/setup.cfg, and I expect this option to be relative to the current directory in which we run pytest.

If we want to alleviate this, we can use a session `go_to_root_dir` fixture before `test_call`, but this might confuse someone attempting to run the tests from a different directory.

**Comment by andfletcher** [comment]
this is done for now.
